import type { ImagePipelineSettings, PipelineEffect } from "./types";

export function createDefaultPipeline(settings: ImagePipelineSettings): PipelineEffect[] {
  return [
    {
      id: "blur",
      type: "blur",
      enabled: settings.blur > 0,
      params: { radius: settings.blur },
    },
    {
      id: "adjust",
      type: "adjust",
      enabled: true,
      params: {
        contrast: settings.contrast,
        brightness: settings.brightness,
        saturation: settings.saturation,
      },
    },
    {
      id: "sharpness",
      type: "sharpness",
      enabled: settings.sharpness > 0,
      params: { amount: settings.sharpness },
    },
    {
      id: "noise",
      type: "noise",
      enabled: settings.noise > 0,
      params: { amount: settings.noise },
    },
    {
      id: "pixelScale",
      type: "pixelScale",
      enabled: settings.pixelSize > 1,
      params: { scale: settings.pixelSize },
    },
    {
      id: "glitch",
      type: "glitch",
      enabled: settings.glitchType !== "None",
      params: {
        palette: settings.palette,
        glitchType: settings.glitchType,
        pixelSortMetric: settings.pixelSortMetric,
        pixelSortMask: settings.pixelSortMask,
        thresholdMin: settings.thresholdMin,
        thresholdMax: settings.thresholdMax,
        angle: settings.angle,
        sortLength: settings.sortLength,
        blockSize: settings.blockSize,
        chaos: settings.chaos,
        quantization: settings.quantization,
        redShiftX: settings.redShiftX,
        redShiftY: settings.redShiftY,
        greenShiftX: settings.greenShiftX,
        greenShiftY: settings.greenShiftY,
        blueShiftX: settings.blueShiftX,
        blueShiftY: settings.blueShiftY,
        globalRgbShiftIntensity: settings.globalRgbShiftIntensity,
        sliceCount: settings.sliceCount,
        maxOffset: settings.maxOffset,
        randomness: settings.randomness,
        scanlineThickness: settings.scanlineThickness,
        scanlineGap: settings.scanlineGap,
        flicker: settings.flicker,
        curvature: settings.curvature,
        snapGlitchToPalette: settings.snapGlitchToPalette,
        paletteMix: settings.paletteMix,
        globalSeed: settings.globalSeed,
      },
    },
    {
      id: "dither",
      type: "dither",
      enabled: settings.algorithm !== "None",
      params: {
        algorithm: settings.algorithm,
        palette: settings.palette,
        customPalette: settings.customPalette,
        intensity: settings.intensity,
      },
    },
  ];
}
